version: "3.9"
services:
  db:
    image: postgres:17
    container_name: takehome-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: ./db_data
      o: bind
